"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from django.core.management.utils import get_random_secret_key
from dotenv import load_dotenv


def _load_local_env_file(env_path: Path) -> None:
    if not env_path.exists():
        return

    load_dotenv(env_path)


    for raw_line in env_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue

        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


def _env_bool(key: str, default: bool = False) -> bool:
    value = os.getenv(key)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def _env_int(key: str, default: int) -> int:
    raw_value = os.getenv(key)
    if raw_value is None:
        return default
    try:
        return int(raw_value)
    except (TypeError, ValueError):
        return default


def _env_list(key: str, default: str = '') -> list[str]:
    raw_value = os.getenv(key, default)
    return [item.strip() for item in raw_value.split(',') if item.strip()]

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
_load_local_env_file(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DEBUG', default=False)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY') or os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = get_random_secret_key()
    else:
        raise ImproperlyConfigured(
            'Missing DJANGO_SECRET_KEY (or SECRET_KEY) environment variable with DEBUG=False.'
        )

ALLOWED_HOSTS = _env_list('ALLOWED_HOSTS', 'localhost,127.0.0.1')
CSRF_TRUSTED_ORIGINS = _env_list(
    'CSRF_TRUSTED_ORIGINS',
    (
        'http://localhost:3000,http://127.0.0.1:3000,'
        'https://localhost:3000,https://127.0.0.1:3000,'
        'http://localhost:8000,http://127.0.0.1:8000,'
        'https://localhost:8000,https://127.0.0.1:8000'
    ),
)

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = _env_bool('USE_X_FORWARDED_HOST', default=not DEBUG)
SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', default=not DEBUG)
SESSION_COOKIE_SECURE = _env_bool('SESSION_COOKIE_SECURE', default=not DEBUG)
CSRF_COOKIE_SECURE = _env_bool('CSRF_COOKIE_SECURE', default=not DEBUG)
SECURE_HSTS_SECONDS = _env_int('SECURE_HSTS_SECONDS', 31536000 if not DEBUG else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=not DEBUG)
SECURE_HSTS_PRELOAD = _env_bool('SECURE_HSTS_PRELOAD', default=not DEBUG)
SECURE_CONTENT_TYPE_NOSNIFF = _env_bool('SECURE_CONTENT_TYPE_NOSNIFF', default=True)
SECURE_REFERRER_POLICY = os.getenv('SECURE_REFERRER_POLICY', 'same-origin')


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.inlines',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'api',
    'core',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

db_engine = os.getenv('DB_ENGINE', 'sqlite').lower()

if db_engine in {'postgres', 'postgresql'}:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'lab_cms'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
            'CONN_MAX_AGE': _env_int('DB_CONN_MAX_AGE', 60),
            'CONN_HEALTH_CHECKS': _env_bool('DB_CONN_HEALTH_CHECKS', default=True),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

API_CACHE_TIMEOUT = _env_int('API_CACHE_TIMEOUT', 60)

default_cors_origins = (
    (
        'http://localhost:3000,http://127.0.0.1:3000,'
        'https://localhost:3000,https://127.0.0.1:3000,'
        'http://localhost:3001,http://127.0.0.1:3001,'
        'https://localhost:3001,https://127.0.0.1:3001'
    )
    if DEBUG
    else ''
)

CORS_ALLOWED_ORIGINS = _env_list('CORS_ALLOWED_ORIGINS', default_cors_origins)

CORS_ALLOWED_ORIGIN_REGEXES = (
    [
        r'^http://localhost(:\d+)?$',
        r'^http://127\.0\.0\.1(:\d+)?$',
        r'^https://localhost(:\d+)?$',
        r'^https://127\.0\.0\.1(:\d+)?$',
    ]
    if DEBUG
    else []
)

CORS_URLS_REGEX = r'^/api/.*$'

UNFOLD = {
    'SITE_TITLE': 'LP2MGI CMS',
    'SITE_HEADER': 'LP2MGI Content Management',
    'SITE_SUBHEADER': 'EST Casablanca',
    'SITE_URL': os.getenv('ADMIN_VIEW_SITE_URL', 'http://localhost:3000/'),
    'SITE_SYMBOL': 'dashboard',
    'SHOW_HISTORY': True,
    'SHOW_VIEW_ON_SITE': True,
    'DASHBOARD_CALLBACK': 'core.admin.dashboard.dashboard_callback',
    'STYLES': [
        '/static/core/css/admin-theme.css',
    ],
    'COLORS': {
        'base': {
            '50': '#f4f8fb',
            '100': '#eaf1f7',
            '200': '#dbe5ef',
            '300': '#c3d1df',
            '400': '#8ca3bb',
            '500': '#52657d',
            '600': '#334155',
            '700': '#1f2e42',
            '800': '#1b3a5c',
            '900': '#13283f',
            '950': '#0b1420',
        },
        'primary': {
            '50': '#ebf8f6',
            '100': '#d5f1ec',
            '200': '#ade4dc',
            '300': '#81d5ca',
            '400': '#54c6b9',
            '500': '#2a9d8f',
            '600': '#218276',
            '700': '#1b6a60',
            '800': '#16544d',
            '900': '#123f3b',
            '950': '#0b2a27',
        },
        'font': {
            'subtle-light': 'var(--color-base-500)',
            'subtle-dark': 'var(--color-base-400)',
            'default-light': 'var(--color-base-600)',
            'default-dark': 'var(--color-base-300)',
            'important-light': 'var(--color-base-900)',
            'important-dark': 'var(--color-base-100)',
        },
    },
    'SIDEBAR': {
        'show_search': True,
        'show_all_applications': False,
        'navigation': [
            {
                'title': 'Dashboard',
                'separator': True,
                'items': [
                    {
                        'title': 'Overview',
                        'icon': 'dashboard',
                        'link': '/admin/',
                    },
                ],
            },
            {
                'title': 'Website Content',
                'items': [
                    {
                        'title': 'Homepage Hero Slides',
                        'icon': 'home',
                        'link': '/admin/core/homeheroslide/',
                    },
                    {
                        'title': 'Overview Page',
                        'icon': 'info',
                        'link': '/admin/core/overviewcontent/',
                    },
                    {
                        'title': 'Site Settings',
                        'icon': 'settings',
                        'link': '/admin/core/sitesettings/',
                    },
                    {
                        'title': 'Homepage Metrics',
                        'icon': 'monitoring',
                        'link': '/admin/core/homemetric/',
                    },
                    {
                        'title': 'News Posts',
                        'icon': 'newspaper',
                        'link': '/admin/core/newspost/',
                    },
                    {
                        'title': 'Content Pages',
                        'icon': 'description',
                        'link': '/admin/core/contentpage/',
                    },
                    {
                        'title': 'Events',
                        'icon': 'event',
                        'link': '/admin/core/event/',
                    },
                    {
                        'title': 'Galleries',
                        'icon': 'photo_library',
                        'link': '/admin/core/gallery/',
                    },
                ],
            },
            {
                'title': 'Research Data',
                'items': [
                    {
                        'title': 'Teams',
                        'icon': 'groups',
                        'link': '/admin/core/team/',
                    },
                    {
                        'title': 'Members',
                        'icon': 'badge',
                        'link': '/admin/core/member/',
                    },
                    {
                        'title': 'Projects',
                        'icon': 'science',
                        'link': '/admin/core/project/',
                    },
                    {
                        'title': 'Publications',
                        'icon': 'menu_book',
                        'link': '/admin/core/publication/',
                    },
                ],
            },
            {
                'title': 'Messages & System',
                'items': [
                    {
                        'title': 'Contact Messages',
                        'icon': 'mail',
                        'link': '/admin/core/contactmessage/',
                    },
                    {
                        'title': 'Users',
                        'icon': 'manage_accounts',
                        'link': '/admin/auth/user/',
                    },
                    {
                        'title': 'Groups',
                        'icon': 'shield',
                        'link': '/admin/auth/group/',
                    },
                ],
            },
        ],
    },
}
