import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
import { Inter } from "next/font/google";

const themeInitScript = `(() => {
  try {
    const savedMode = localStorage.getItem('theme-mode');
    const validMode = savedMode === 'light' || savedMode === 'dark' || savedMode === 'system';

    if (!validMode || savedMode === 'system') {
      document.documentElement.removeAttribute('data-theme');
      return;
    }

    document.documentElement.setAttribute('data-theme', savedMode);
  } catch (_) {
    document.documentElement.removeAttribute('data-theme');
  }
})();`;

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
      </head>
      <body
        className={`${inter.className} antialiased leading-relaxed`}
      >
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}


