# Generated by Django 6.0.3 on 2026-04-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contentpage_event_gallery_galleryimage_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
