# Generated by Django 6.0.3 on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_team_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="biography",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="member",
            name="google_scholar_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="member",
            name="highlight_quote",
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name="member",
            name="milestones",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="member",
            name="orcid_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="member",
            name="research_interests",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="member",
            name="researchgate_url",
            field=models.URLField(blank=True),
        ),
    ]
