# Generated by Django 6.0.3 on 2026-04-02 23:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_member_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image_url',
            field=models.ImageField(upload_to=core.models.gallery_image_upload_to),
        ),
        migrations.AlterField(
            model_name='homehero',
            name='background_image_url',
            field=models.ImageField(blank=True, upload_to=core.models.home_hero_background_upload_to),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo_url',
            field=models.ImageField(blank=True, upload_to=core.models.member_photo_upload_to),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='cover_image_url',
            field=models.ImageField(blank=True, upload_to=core.models.news_cover_upload_to),
        ),
    ]
