# Generated by Django 6.0.3 on 2026-04-06 00:00

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_galleryimage_image_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OverviewContent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("header_subtitle", models.CharField(blank=True, max_length=120)),
                ("header_title", models.CharField(max_length=255)),
                ("header_description", models.TextField(blank=True)),
                ("director_name", models.CharField(blank=True, max_length=180)),
                ("director_role", models.CharField(blank=True, max_length=180)),
                ("director_photo", models.ImageField(blank=True, upload_to=core.models.overview_director_photo_upload_to)),
                ("director_intro", models.TextField(blank=True)),
                ("director_quote", models.TextField(blank=True)),
                ("director_body", models.TextField(blank=True)),
                ("mission_title", models.CharField(default="Our Mission", max_length=120)),
                ("mission_description", models.TextField(blank=True)),
                ("mission_points", models.JSONField(blank=True, default=list)),
                ("vision_title", models.CharField(default="Our Vision", max_length=120)),
                ("vision_description", models.TextField(blank=True)),
                ("vision_points", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
