# Generated by Django 6.0.3 on 2026-04-12 14:06

import core.models
import django.db.models.deletion
from django.db import migrations, models


def backfill_home_hero_slides(apps, schema_editor):
    HomeHero = apps.get_model('core', 'HomeHero')
    HomeHeroSlide = apps.get_model('core', 'HomeHeroSlide')

    for hero in HomeHero.objects.all().iterator():
        if HomeHeroSlide.objects.filter(hero=hero).exists():
            continue

        HomeHeroSlide.objects.create(
            hero=hero,
            small_label=hero.subtitle,
            big_title=hero.title,
            short_description=hero.description,
            media_type='illustration' if hero.background_image_url else 'none',
            illustration=str(hero.background_image_url) if hero.background_image_url else '',
            use_abstract_background=not bool(hero.background_image_url),
            primary_button_label=hero.button_label,
            primary_button_target_type='url',
            primary_button_url=hero.button_link,
            order=0,
            is_active=hero.is_active,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('small_label', models.CharField(blank=True, max_length=120)),
                ('big_title', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('illustration', 'Illustration'), ('video', 'Video'), ('none', 'None')], default='none', max_length=20)),
                ('illustration', models.ImageField(blank=True, upload_to=core.models.home_hero_slide_illustration_upload_to)),
                ('video_file', models.FileField(blank=True, upload_to=core.models.home_hero_slide_video_upload_to)),
                ('use_abstract_background', models.BooleanField(default=False)),
                ('primary_button_label', models.CharField(blank=True, max_length=80)),
                ('primary_button_target_type', models.CharField(choices=[('url', 'URL'), ('file', 'File')], default='url', max_length=10)),
                ('primary_button_url', models.CharField(blank=True, max_length=255)),
                ('primary_button_file', models.FileField(blank=True, upload_to=core.models.home_hero_slide_button_file_upload_to)),
                ('secondary_button_label', models.CharField(blank=True, max_length=80)),
                ('secondary_button_target_type', models.CharField(choices=[('url', 'URL'), ('file', 'File')], default='url', max_length=10)),
                ('secondary_button_url', models.CharField(blank=True, max_length=255)),
                ('secondary_button_file', models.FileField(blank=True, upload_to=core.models.home_hero_slide_button_file_upload_to)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='core.homehero')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(backfill_home_hero_slides, migrations.RunPython.noop),
    ]
