# Generated by Django 6.0.3 on 2026-04-14 02:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_member_profile_edit_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofilesubmission',
            name='proposed_photo',
            field=models.ImageField(blank=True, upload_to=core.models.member_submission_photo_upload_to),
        ),
    ]
